"""The xlsx export keeps cells numeric and formats them with Excel number formats."""
import io
import os

import pytest

pytest.importorskip("pandas")
openpyxl = pytest.importorskip("openpyxl")
pytest.importorskip("fastapi")
pytest.importorskip("motor")

os.environ.setdefault("MONGO_URL", "mongodb://localhost:27017")
os.environ.setdefault("DB_NAME", "export_test")

import server  # noqa: E402

RESULTS = {
    "reporting_currency": "EUR",
    "arr": {"value": 3129104.4, "mrr": 260758.7, "month": "2026-06"},
    "nrr": {"overall_pct": 106.41, "n": 100, "by_segment": {}, "by_cohort": {}, "series": []},
    "gross_churn": {"overall_pct": 8.38},
    "sales_cycle": {"median_days": 42.1, "n": 12},
    "win_rate": {"win_rate_pct": 50.0, "excluded_invalid": 0},
    "cac_payback": {"default_l": 1, "headline_quarter": "2026-Q1", "quarters": {
        "2026-Q1": {
            "new_mrr": 1000.4, "gross_margin_pct": 71.2, "months_in_quarter": 3, "partial": False,
            "L0": {"months": None, "reason": "x"}, "L2": {"months": None, "reason": "x"},
            "L1": {"months": 12.24, "sm_expense": 9000.0, "reason": None}},
        "2026-Q2": {
            "new_mrr": 400.0, "gross_margin_pct": 70.0, "months_in_quarter": 2, "partial": True,
            "L0": {"months": None, "reason": "x"}, "L2": {"months": None, "reason": "x"},
            "L1": {"months": 30.0, "sm_expense": 9000.0, "reason": None}}}},
    "acv_path": {"current_customers": 24, "current_arr": 3129104.4, "acv": 130379.35,
                 "target_arr": 5000000, "target_date": "2027-12-31", "total_customers_at_target": 128.3, "additional_customers_needed": 104.3,
                 "required_net_new_per_year": 60.1, "observed_net_new_per_year_12m": 6.0,
                 "observed_net_new_per_year_24m": 3.0, "required_vs_observed_12m": 1.28,
                 "required_vs_observed_24m": 1.685, "bands": [], "by_segment": {}},
    "anomalies": {}, "missing_data": [],
}


def _cell(ws, label):
    for row in ws.iter_rows(min_row=2):
        if row[0].value and str(row[0].value).startswith(label):
            return row[1]
    raise AssertionError(f"no row {label!r}")


def test_cells_are_numeric_with_number_formats():
    wb = openpyxl.load_workbook(server.build_export_workbook({"company_name": "Acme"}, RESULTS))
    head, path = wb["Headline"], wb["Path to Plan"]

    arr = _cell(head, "Ending ARR")
    assert arr.value == 3129104.4 and arr.number_format == "#,##0"
    nrr = _cell(head, "NRR overall")
    assert nrr.value == pytest.approx(1.0641) and nrr.number_format == "0%"
    cac = _cell(head, "CAC payback")
    assert cac.value == 12.24 and cac.number_format == "0.0"
    days = _cell(head, "Median sales cycle")
    assert days.value == 43 and days.number_format == "#,##0"

    total = _cell(path, "Total customers at target ARR")
    assert total.value == 129 and total.number_format == "#,##0"
    added = _cell(path, "Additional customers needed")
    assert added.value == 105 and added.number_format == "#,##0", "the gap is shown beside the total, rounded up"
    ratio = _cell(path, "Required ÷ observed (24m)")
    assert ratio.value == 1.685 and ratio.number_format == '0.00"x"'

    for ws in (head, path):  # no formatted strings in any value cell
        for row in ws.iter_rows(min_row=2):
            assert not (isinstance(row[1].value, str) and any(ch in row[1].value for ch in "%x,")
                        and row[0].value not in ("Company", "Reporting currency")), row[0].value


def test_disclosure_block_sits_at_the_foot_of_the_headline_sheet():
    text = "Narrative generated by claude-opus-5 on 2026-09-30 14:07 UTC."
    wb = openpyxl.load_workbook(server.build_export_workbook({"company_name": "Acme"}, RESULTS, text))
    ws = wb["Headline"]
    last = [c for c in ws["A"] if c.value][-1]
    assert last.value == "AI disclosure"
    assert ws.cell(row=last.row, column=2).value == text
    # prompt version never appears in the workbook
    assert not any("prompt" in str(c.value).lower() for row in ws.iter_rows() for c in row if c.value)


def test_no_disclosure_row_when_no_narrative_exists():
    wb = openpyxl.load_workbook(server.build_export_workbook({"company_name": "Acme"}, RESULTS))
    assert "AI disclosure" not in [c.value for c in wb["Headline"]["A"]]


def test_headline_cac_is_the_latest_complete_quarter_and_names_it():
    wb = openpyxl.load_workbook(server.build_export_workbook({"company_name": "Acme"}, RESULTS))
    cac = _cell(wb["Headline"], "CAC payback")
    label = next(r[0].value for r in wb["Headline"].iter_rows(min_row=2) if str(r[0].value).startswith("CAC payback"))
    assert cac.value == 12.24, "the partial 2026-Q2 figure (30.0) must not headline"
    assert "2026-Q1" in label and "latest complete quarter" in label


def test_quarterly_sheet_labels_the_partial_quarter():
    wb = openpyxl.load_workbook(server.build_export_workbook({"company_name": "Acme"}, RESULTS))
    ws = wb["CAC by Quarter"]
    status = {row[0].value: row[1].value for row in ws.iter_rows(min_row=2)}
    assert status == {"2026-Q1": "complete", "2026-Q2": "partial (2 of 3 months)"}


def test_no_complete_quarter_is_stated_not_filled_with_a_partial_figure():
    results = {**RESULTS, "cac_payback": {"default_l": 1, "headline_quarter": None, "quarters": {
        "2026-Q2": {"new_mrr": 400.0, "gross_margin_pct": 70.0, "months_in_quarter": 2, "partial": True,
                    "L0": {"months": None, "reason": "x"}, "L2": {"months": None, "reason": "x"},
                    "L1": {"months": 30.0, "sm_expense": 9000.0, "reason": None}}}}}
    wb = openpyxl.load_workbook(server.build_export_workbook({"company_name": "Acme"}, results))
    rows = {str(r[0].value): r[1].value for r in wb["Headline"].iter_rows(min_row=2)}
    assert rows["CAC payback (no complete quarter, months)"] is None


def _segment_results(**kw):
    import sys
    from pathlib import Path
    sys.path.insert(0, str(Path(__file__).parents[1]))
    import test_growth_engine as tge
    _, years, base = tge._seg_paths(target_arr=1_000_000)
    sp = tge._seg_paths(target_arr=base + 25_000 * 3 * years, **kw)[0]
    return {**RESULTS, "segment_paths": sp}, sp


def test_segment_sheets_keep_cells_numeric_with_number_formats():
    results, sp = _segment_results()
    wb = openpyxl.load_workbook(server.build_export_workbook({"company_name": "Acme"}, results))
    ws = wb["Segment Base"]
    assert "not a forecast" in ws["A1"].value, "the assumption heads the sheet"
    header = [c.value for c in ws[2]]
    row = {h: c for h, c in zip(header, ws[3])}            # first segment row (A)
    assert row["Segment"].value == "A"
    proj = row["Projected ARR (at constant NRR, EUR)"]
    assert proj.value == pytest.approx(sp["stage_one"]["segments"]["A"]["projected_arr"]) and proj.number_format == "#,##0"
    nrr = row["NRR (trailing 12 months)"]
    assert nrr.value == pytest.approx(1.25) and nrr.number_format == "0%"
    erosion = {h: c for h, c in zip(header, ws[4])}["Change in ARR (at constant NRR, EUR)"]
    assert erosion.value < 0, "segment B's erosion is shown, not netted away"
    for row_ in ws.iter_rows(min_row=3):
        assert not any(isinstance(c.value, str) and "%" in c.value for c in row_)


def test_segment_mix_sheet_states_the_verdict_and_stays_numeric():
    results, sp = _segment_results()
    wb = openpyxl.load_workbook(server.build_export_workbook({"company_name": "Acme"}, results))
    rows = {str(r[0].value): r[1] for r in wb["Segment Mix"].iter_rows(min_row=2)}
    assert rows["Any segment mix reaches it (12-month window)"].value == "yes"
    need = rows["Required blended landed ACV (12-month window, EUR)"]
    assert need.value == pytest.approx(25_000) and need.number_format == "#,##0"
    # the 24-month window is said to be unavailable, not left out
    assert "24-month" in "".join(rows) and "24 months" in str(rows["Reverse-solve (24-month window)"].value)
    detail = wb["Segment Mix Detail"]
    assert [c.value for c in detail[1]][:2] == ["Window (months)", "Segment"]
    shifts = [r[6].value for r in detail.iter_rows(min_row=2)]
    assert any(v and v > 0 for v in shifts) and any(v and v < 0 for v in shifts)
    assert detail["G2"].number_format == "0%"


def test_unavailable_segment_paths_name_what_would_resolve_them():
    import sys
    from pathlib import Path
    sys.path.insert(0, str(Path(__file__).parents[1]))
    import test_growth_engine as tge
    sp = tge._seg_paths(target_arr=1_000_000, no_segments=True)[0]
    wb = openpyxl.load_workbook(server.build_export_workbook({"company_name": "Acme"}, {**RESULTS, "segment_paths": sp}))
    values = [c.value for row in wb["Segment Base"].iter_rows() for c in row]
    assert "segment" in " ".join(str(v) for v in values if v)


def test_results_stored_before_the_rename_still_export_the_total_under_its_new_name():
    legacy = {**RESULTS, "acv_path": {k: v for k, v in RESULTS["acv_path"].items()
                                      if k not in ("total_customers_at_target", "additional_customers_needed")}}
    legacy["acv_path"]["customers_needed"] = 128.3
    wb = openpyxl.load_workbook(server.build_export_workbook({"company_name": "Acme"}, legacy))
    path = wb["Path to Plan"]
    assert _cell(path, "Total customers at target ARR").value == 129
    assert _cell(path, "Additional customers needed").value is None      # not derived, not invented


# ---------------------------------------------------------------------------
# Label rule: a name is text plus, at most, brackets. No comma outside a bracket,
# so none can sit before one ("CAC payback, months (2026-Q1)" was the offender).
# ---------------------------------------------------------------------------
import re as _re

_KV_SHEETS = {"Headline", "Path to Plan", "Segment Mix"}
_TITLE_ROW_SHEETS = {"ACV Bands", "Segment Base"}     # a title sentence sits in row 1, headers in row 2


def _export_labels(wb):
    """(sheet, label) for every row label and column header - never values or notes."""
    out = []
    for ws in wb.worksheets:
        if ws.title in _KV_SHEETS:
            cells = [r[0] for r in ws.iter_rows(min_row=2) if r[0].value]
        elif ws.title in _TITLE_ROW_SHEETS:
            cells = [c for c in ws[2] if c.value]
        else:
            cells = [c for c in ws[1] if c.value]
        out += [(ws.title, str(c.value)) for c in cells]
    return out


def _breaks_label_rule(label):
    outside_brackets = _re.sub(r"\([^)]*\)", "", label)
    return "," in outside_brackets or ", (" in label or ",(" in label


def test_no_export_label_has_a_comma_outside_its_brackets():
    results, _ = _segment_results()
    wb = openpyxl.load_workbook(server.build_export_workbook(
        {"company_name": "Acme"}, results, "Narrative generated by claude-opus-5 on 2026-09-30 14:07 UTC."))
    labels = _export_labels(wb)
    assert len(labels) > 60, "the check must actually see the labels"
    assert [x for x in labels if _breaks_label_rule(x[1])] == []


def test_no_export_label_breaks_the_rule_when_there_is_no_complete_cac_quarter():
    results = {**RESULTS, "cac_payback": {"default_l": 1, "headline_quarter": None, "quarters": {
        "2026-Q2": {"new_mrr": 400.0, "gross_margin_pct": 70.0, "months_in_quarter": 2, "partial": True,
                    "L0": {"months": None, "reason": "x"}, "L2": {"months": None, "reason": "x"},
                    "L1": {"months": 30.0, "sm_expense": 9000.0, "reason": None}}}}}
    wb = openpyxl.load_workbook(server.build_export_workbook({"company_name": "Acme"}, results))
    labels = [l for _, l in _export_labels(wb)]
    assert "CAC payback (no complete quarter, months)" in labels
    assert [l for l in labels if _breaks_label_rule(l)] == []


def test_headline_cac_label_and_its_lag_row():
    wb = openpyxl.load_workbook(server.build_export_workbook({"company_name": "Acme"}, RESULTS))
    rows = {str(r[0].value): r[1] for r in wb["Headline"].iter_rows(min_row=2)}
    assert rows["CAC payback (2026-Q1, latest complete quarter, months)"].value == 12.24
    lag = rows["S&M spend lag used for CAC payback (quarters)"]
    assert lag.value == 1 and lag.number_format == "0", "the lag left the label but is still shown"


# ---------------------------------------------------------------------------
# Narrative sheets: one per generated narrative, with its period and where the numbers are
# ---------------------------------------------------------------------------
def _narrative(step="growth_engine", **over):
    from app.llm.schemas import Narrative, NarrativeResponse, TableRow
    n = Narrative(
        headline="Ending ARR is 3,129,104 EUR and NRR is 106%.",
        what_this_means="Net revenue retention above 100% means the existing base is growing.",
        table_rows=[
            TableRow(label="Ending ARR", value="3,129,104 EUR", source_key="metrics.arr.value"),
            TableRow(label="NRR", value="106%", source_key="metrics.nrr.overall_pct"),
            TableRow(label="Additional", value="756", source_key="metrics.acv_path.additional_customers_needed"),
            TableRow(label="Cohort", value="96%", source_key="metrics.cohort_retention.data.values.3"),
        ],
        worth_flagging=["Enterprise NRR rests on 8 customers."],
        next_actions=["Ask for the contract list.", "Confirm the segment mapping."],
        source_keys=["metrics.arr.value", "metrics.nrr.overall_pct"],
        **over,
    )
    return NarrativeResponse(run_id="r", step=step, narrative_status="ok", narrative=n,
                             model="claude-opus-5", generated_at="2026-09-30T14:07:45+00:00")


_META = {"company_name": "Acme", "as_of_month": "2026-06", "target_arr": 5_000_000, "target_date": "2027-12-31"}


def _sheet_rows(ws):
    return [[c.value for c in row] for row in ws.iter_rows()]


def test_a_narrative_sheet_is_written_after_the_headline_sheet_for_each_generated_step():
    wb = openpyxl.load_workbook(server.build_export_workbook(
        _META, RESULTS, None, [_narrative("growth_engine"), _narrative("path_to_plan")]))
    assert wb.sheetnames[:3] == ["Headline", "Narrative - Growth engine", "Narrative - Path to plan"]


def test_no_narrative_no_narrative_sheet():
    wb = openpyxl.load_workbook(server.build_export_workbook(_META, RESULTS))
    assert not [n for n in wb.sheetnames if n.startswith("Narrative")]


def test_the_sheet_states_the_period_and_target_it_was_written_against():
    ws = openpyxl.load_workbook(server.build_export_workbook(_META, RESULTS, None, [_narrative()]))["Narrative - Growth engine"]
    rows = {r[0]: r[1] for r in _sheet_rows(ws) if r[0]}
    assert rows["As-of month"] == "2026-06 (data through 2026-06-30)"
    assert rows["Target ARR and date"] == "5,000,000 EUR by 2027-12-31"
    top = [r[0] for r in _sheet_rows(ws)[:5]]
    assert top[:1] == ["Growth engine narrative"] and "As-of month" in top, "the period is at the top, not buried"


def test_the_six_sections_are_each_their_own_section():
    ws = openpyxl.load_workbook(server.build_export_workbook(_META, RESULTS, None, [_narrative()]))["Narrative - Growth engine"]
    values = _sheet_rows(ws)
    sections = [r[0] for r in values if r[0] in (
        "Headline", "What this means", "Evidence table", "Worth flagging", "Next actions", "Source keys")]
    assert sections == ["Headline", "What this means", "Evidence table", "Worth flagging", "Next actions", "Source keys"]
    by = {r[0]: r[1] for r in values if r[0]}
    assert by["Headline"] == "Ending ARR is 3,129,104 EUR and NRR is 106%."
    assert by["What this means"].startswith("Net revenue retention above 100%")
    assert by["Worth flagging"] == "1. Enterprise NRR rests on 8 customers."
    flat = [c for r in values for c in r if c]
    assert "1. Ask for the contract list." in flat and "2. Confirm the segment mapping." in flat
    assert "metrics.arr.value" in flat


def test_evidence_rows_use_readable_names_keep_the_path_and_name_the_sheet_holding_the_number():
    ws = openpyxl.load_workbook(server.build_export_workbook(_META, RESULTS, None, [_narrative()]))["Narrative - Growth engine"]
    values = _sheet_rows(ws)
    head = next(i for i, r in enumerate(values) if r[:4] == ["Metric", "Value", "Source key", "Where to find the number"])
    rows = {r[2]: r for r in values[head + 1: head + 5]}
    assert rows["metrics.arr.value"] == ["Ending ARR (latest month MRR × 12)", "3,129,104 EUR", "metrics.arr.value", "Headline"]
    assert rows["metrics.nrr.overall_pct"][0] == "NRR (trailing 12 months)" and rows["metrics.nrr.overall_pct"][3] == "Headline"
    assert rows["metrics.acv_path.additional_customers_needed"][3] == "Path to Plan"
    # The cohort grid is not written to any sheet, so the row says so instead of pointing at a neighbour.
    assert rows["metrics.cohort_retention.data.values.3"][3] == "not on a data sheet"


def test_a_flagged_narrative_carries_its_warning_onto_the_sheet():
    n = _narrative()
    n.narrative_status, n.unmatched_numbers = "flagged", ["42.7"]
    ws = openpyxl.load_workbook(server.build_export_workbook(_META, RESULTS, None, [n]))["Narrative - Growth engine"]
    text = " ".join(str(c) for r in _sheet_rows(ws) for c in r if c)
    assert "Unverified figures in this text: 42.7" in text


def test_narrative_text_beginning_with_an_equals_sign_is_text_not_a_formula():
    n = _narrative()
    n.narrative = n.narrative.model_copy(update={"headline": "=HYPERLINK(\"http://example.com\",\"click\")"})
    ws = openpyxl.load_workbook(server.build_export_workbook(_META, RESULTS, None, [n]))["Narrative - Growth engine"]
    cell = next(c for row in ws.iter_rows() for c in row if c.value and "HYPERLINK" in str(c.value))
    assert cell.data_type == "s"


def test_prompt_version_never_appears_on_a_narrative_sheet():
    ws = openpyxl.load_workbook(server.build_export_workbook(_META, RESULTS, None, [_narrative()]))["Narrative - Growth engine"]
    text = " ".join(str(c).lower() for r in _sheet_rows(ws) for c in r if c)
    assert "prompt" not in text and " v4" not in text


def test_every_sheet_a_source_key_can_point_to_exists_in_a_full_export():
    """data_sheet_for can only name a sheet the workbook really has."""
    from app import narrative_export as ne
    results, _ = _segment_results()
    names = set(openpyxl.load_workbook(server.build_export_workbook(
        _META, {**results, "anomalies": {"negative_mrr_months": []}, "missing_data": []},
        "x", [_narrative()])).sheetnames)
    assert set(ne.DATA_SHEETS) <= names, sorted(set(ne.DATA_SHEETS) - names)


def test_data_sheet_for_names_the_sheet_that_carries_each_kind_of_value():
    from app import narrative_export as ne
    cases = {
        "metrics.arr.value": "Headline",
        "metrics.gross_churn.overall_pct": "Headline",
        "metrics.nrr.by_segment.SMB.nrr_pct": "By Segment",
        "metrics.sales_cycle.by_segment.SMB.median_days": "By Segment",
        "metrics.acv_path.by_segment.SMB.acv": "By Segment",
        "metrics.nrr.by_cohort.2025-Q1.nrr_pct": "NRR by Cohort",
        "metrics.nrr.series.nrr_pct": "NRR Series",
        "metrics.cac_payback.quarters.2026-Q1.L1.months": "CAC by Quarter",
        "metrics.acv_path.total_customers_at_target": "Path to Plan",
        "metrics.acv_path.bands.count": "ACV Bands",
        "metrics.segment_paths.stage_one.segments.A.projected_arr": "Segment Base",
        "metrics.segment_paths.gap_arr": "Segment Mix",
        "metrics.segment_paths.reverse_solve.12.required_blended_landed_acv": "Segment Mix",
        "metrics.segment_paths.reverse_solve.12.by_segment.A.required_mix_pct": "Segment Mix Detail",
        "acv": "Path to Plan",                                     # a bare leaf the guard also accepts
        "metrics.sales_cycle.iqr": "not on a data sheet",            # the export has the median only
        "metrics.win_rate.won": "not on a data sheet",
        "metrics.cohort_retention.data.values.3": "not on a data sheet",
    }
    assert {k: ne.data_sheet_for(k, {}) for k in cases} == cases


# ---------------------------------------------------------------------------
# The label convention across the whole workbook, and the glossary that now holds ACV's definition
# ---------------------------------------------------------------------------
_GROUP2 = _re.compile(r"\(([^)]*)\)")


def _rich_export():
    results, _ = _segment_results()
    results = {**results, "anomalies": {"negative_mrr_months": [], "revenue_gap_then_resume": [],
                                        "revenue_missing_customer_id": {"count": 0},
                                        "deals_close_before_created": {"excluded_count": 0}}}
    return openpyxl.load_workbook(server.build_export_workbook(
        _META, results, "Narrative generated by claude-opus-5 on 2026-09-30 14:07 UTC.", [_narrative()]))


def test_every_export_label_has_at_most_one_bracket_group():
    labels = _export_labels(_rich_export())
    assert len(labels) > 60
    assert [x for x in labels if len(_GROUP2.findall(x[1])) > 1] == []


def test_a_currency_or_unit_in_an_export_label_is_the_last_part_of_its_bracket():
    ccy = "EUR"
    bad = []
    for sheet, label in _export_labels(_rich_export()):
        for inner in _GROUP2.findall(label):
            parts = [p.strip() for p in inner.split(",")]
            if ccy in parts and parts[-1] != ccy:
                bad.append((sheet, label))
    assert bad == []
    labels = [l for _, l in _export_labels(_rich_export())]
    assert "Projected ARR (at constant NRR, EUR)" in labels
    assert "Required blended landed ACV (12-month window, EUR)" in labels
    assert "Total mix moved (12-month window, percentage points)" in labels
    assert "ACV (ARR ÷ active customers, EUR)" in labels


def test_no_export_label_carries_the_acv_definition():
    labels = [l for _, l in _export_labels(_rich_export())]
    assert [l for l in labels if "average contract value" in l] == []
    assert any(l.startswith("ACV (") for l in labels)


def test_the_glossary_sheet_is_in_every_export_and_defines_acv():
    """It is the only definition of ACV in the workbook, so it must never depend on what else is there."""
    variants = {
        "empty results": ({}, {}, None, None),
        "core results only": (_META, RESULTS, None, None),
        "with narratives and disclosure": (_META, RESULTS, "Narrative generated by x on y.", [_narrative()]),
        "with segment paths": (_META, _segment_results()[0], None, None),
        "no segment column": (_META, {**RESULTS, "segment_paths": {"available": False, "missing_inputs": [
            {"input": "customer segments", "resolve": "Map the optional 'segment' column"}]}}, None, None),
    }
    for name, (meta, results, disclosure_text, narratives) in variants.items():
        wb = openpyxl.load_workbook(server.build_export_workbook(meta, results, disclosure_text, narratives))
        assert "Glossary" in wb.sheetnames, name
        assert wb.sheetnames[-1] == "Glossary", f"{name}: the glossary stays last"
        terms = {r[0].value: r[1].value for r in wb["Glossary"].iter_rows(min_row=2)}
        assert terms["ACV"] == "average contract value", name
        assert "first-month ARR" in terms["Landed ACV"], name
        assert [c.value for c in wb["Glossary"][1]] == ["Term", "Definition"], name
