"""The AI-provenance disclosure block: model and generation time, no prompt version."""
from app import disclosure as d


def _section(step, model, when):
    return {"step": step, "model": model, "generated_at": when}


def test_time_is_shown_to_the_minute_in_utc():
    assert d.format_generated_at("2026-09-30T14:07:45.123456+00:00") == "2026-09-30 14:07 UTC"
    assert d.format_generated_at("2026-09-30T16:07:00+02:00") == "2026-09-30 14:07 UTC"
    assert d.format_generated_at("2026-09-30T14:07:00Z") == "2026-09-30 14:07 UTC"
    assert d.format_generated_at(None) is None and d.format_generated_at("nonsense") is None


def test_single_section():
    b = d.build_disclosure([_section("growth_engine", "claude-opus-5", "2026-09-30T14:07:45+00:00")])
    assert b["text"] == "Narrative generated by claude-opus-5 on 2026-09-30 14:07 UTC."
    assert b["mixed_models"] is False and b["models"] == ["claude-opus-5"]


def test_same_model_same_minute_is_one_sentence():
    b = d.build_disclosure([
        _section("growth_engine", "claude-opus-5", "2026-09-30T14:07:01+00:00"),
        _section("path_to_plan", "claude-opus-5", "2026-09-30T14:07:59+00:00"),
    ])
    assert b["text"] == "Narrative generated by claude-opus-5 on 2026-09-30 14:07 UTC."


def test_same_model_different_times_lists_sections():
    b = d.build_disclosure([
        _section("growth_engine", "claude-opus-5", "2026-09-28T09:12:00+00:00"),
        _section("path_to_plan", "claude-opus-5", "2026-09-30T14:07:00+00:00"),
    ])
    assert b["mixed_models"] is False
    assert b["text"] == (
        "Narrative generated by claude-opus-5. Sections generated: "
        "Growth engine 2026-09-28 09:12 UTC; Path to plan 2026-09-30 14:07 UTC."
    )


def test_different_models_are_stated_not_collapsed_to_one():
    b = d.build_disclosure([
        _section("growth_engine", "claude-opus-5", "2026-09-28T09:12:00+00:00"),
        _section("cohort_retention", "claude-sonnet-5", "2026-09-30T14:07:00+00:00"),
    ])
    assert b["mixed_models"] is True
    assert b["models"] == ["claude-opus-5", "claude-sonnet-5"]
    assert b["text"].startswith("Sections were generated by different models.")
    assert "Growth engine: claude-opus-5, 2026-09-28 09:12 UTC" in b["text"]
    assert "Cohort retention: claude-sonnet-5, 2026-09-30 14:07 UTC" in b["text"]


def test_nothing_to_disclose_when_no_narrative_exists():
    assert d.build_disclosure([]) is None
    assert d.build_disclosure([_section("growth_engine", None, None)]) is None


def test_prompt_version_is_not_part_of_the_block():
    b = d.build_disclosure([{**_section("growth_engine", "claude-opus-5", "2026-09-30T14:07:00+00:00"),
                             "prompt_version": "v4"}])
    assert "v4" not in b["text"] and "prompt" not in b["text"].lower()
    assert all("prompt_version" not in row for row in b["sections"])
