"""The AI-provenance disclosure shown at the foot of the analysis and exports.

One block, built in one place, so the dashboard, the IC memo export and the xlsx
export all say the same thing. It states which model wrote the narrative and when,
to the minute. Prompt version is deliberately absent: it stays in the audit trail
(`llm_calls`, `llm_narratives`) and is not shown to readers.

If sections were written by different models the block says so and lists them,
rather than presenting one model as if it covered everything.
"""
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

STEP_LABELS = {
    "growth_engine": "Growth engine",
    "cohort_retention": "Cohort retention",
    "cac_efficiency": "CAC efficiency",
    "path_to_plan": "Path to plan",
}


def format_generated_at(value: Optional[str]) -> Optional[str]:
    """ISO timestamp -> "2026-09-30 14:07 UTC" (date, hour and minute; UTC)."""
    if not value:
        return None
    try:
        dt = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except ValueError:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def build_disclosure(sections: List[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    """`sections`: [{"step", "model", "generated_at"}] for narratives that exist.

    Returns {"text", "models", "mixed_models", "sections"} or None when there are
    no narratives, in which case there is nothing to disclose.
    """
    rows = []
    for s in sections:
        when = format_generated_at(s.get("generated_at"))
        model = s.get("model")
        if not model or not when:
            continue
        rows.append({
            "step": s.get("step"),
            "section": STEP_LABELS.get(s.get("step"), str(s.get("step")).replace("_", " ").capitalize()),
            "model": model,
            "generated_at": when,
        })
    if not rows:
        return None

    models = sorted({r["model"] for r in rows})
    mixed = len(models) > 1
    times = {r["generated_at"] for r in rows}

    if mixed:
        parts = "; ".join(f"{r['section']}: {r['model']}, {r['generated_at']}" for r in rows)
        text = f"Sections were generated by different models. {parts}."
    elif len(times) == 1:
        text = f"Narrative generated by {models[0]} on {rows[0]['generated_at']}."
    else:
        parts = "; ".join(f"{r['section']} {r['generated_at']}" for r in rows)
        text = f"Narrative generated by {models[0]}. Sections generated: {parts}."

    return {"text": text, "models": models, "mixed_models": mixed, "sections": rows}
